{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-oidc-callout.fullname" . }}
  labels:
    {{- include "nats-oidc-callout.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.config.values | nindent 4 }}
{{- end }}
