{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "nats-oidc-callout.fullname" .) }}
  labels:
    {{- include "nats-oidc-callout.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "nats-oidc-callout.selectorLabels" . | nindent 4 }}
{{- end }}
